### ISSUE TITLE
参与贡献

### ISSUE THREAD

**Issue by Viper373** [huhu415/eduData-GoBack#1]
博主你好，我也是一名应届毕业生，7月刚参加工作。
在校期间有三年爬虫经验，目前在职爬虫工程师。我想为该项目贡献代码（我使用的语言为Python）。
若批准，具体细节请联系我：2020311228@bipt.edu.cn

**Comment by huhu415** [comment]
非常欢迎啊

**Comment by Viper373** [comment]
> 非常欢迎啊

可以为我们以后的开发团队搞个群之类的交流平台吗[狗头~]

**Comment by huhu415** [comment]
可以啊, 有一个qq群, 656803742你可以进去看一下
